language: java
env:
  global:
addons:
  ssh_known_hosts:
before_install:
  - env
  - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn package -DskipTests=true
  - docker build -t $DOCKER_USERNAME/$TRAVIS_REPO_SLUG:$TRAVIS_BUILD_NUMBER .
  - docker push $DOCKER_USERNAME/$TRAVIS_REPO_SLUG:$TRAVIS_BUILD_NUMBER
after_success:
  - bash < (curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
      - 445172495@qq.com
    on_success: always
    on_failure: always
